### PR TITLE
Allow usage of kernel headers

### PR DESCRIPTION
**Pull request by mikeNG**
Change-Id: I9fa11bd72fa632551679d8b13a89cccbaae53e77

### CODE REVIEW

**Comment by mikeNG** [comment]
Needed, else build fails: https://github.com/LegacyXperia/local_manifests/commit/ebfc36843d3754eceb01259a03c3064f46186825#commitcomment-4241047

**Comment by mikeNG** [comment]
Any change to merge this?

**Comment by arco** [comment]
Oh, I thought I already did... Sorry, I'll do it as soon as I get home.

**Comment by mikeNG** [comment]
No problem :)

**Pull request closed without merging**
