### PR TITLE
Revert "gralloc : apply kernel 3.4 fb screeninfo type" - Fix LiveWallpaper animating to fast

### PR DESCRIPTION
**Pull request by Albinoman887**
This reverts commit 7071048395405b7407c03c545e0ad9884fd60317.

without this revert live wallpaper goes really fast. can be observed with the PhaseBeam wallpaper (included with cm/aosp) reverting this fixes it.

### CODE REVIEW

**Comment by Albinoman887** [comment]
I/gralloc (  118): using (fd=21)
I/gralloc (  118): id           = msmfb40_90201
I/gralloc (  118): xres         = 540 px
I/gralloc (  118): yres         = 960 px
I/gralloc (  118): xres_virtual = 544 px
I/gralloc (  118): yres_virtual = 2880 px
I/gralloc (  118): bpp          = 32
I/gralloc (  118): r            =  0:8
I/gralloc (  118): g            =  8:8
I/gralloc (  118): b            = 16:8
I/gralloc (  118): width        = 53 mm (258.792450 dpi)
I/gralloc (  118): height       = 95 mm (256.673676 dpi)
I/gralloc (  118): refresh rate = 1986356224.00 Hz
D/CALCFPS (  118): DEBUG_CALC_FPS: 0
D/CALCFPS (  118): period: 10
D/CALCFPS (  118): ignorethresh_us: 500000
D/CALCFPS (  118): DEBUG_CALC_FPS: 0
D/CALCFPS (  118): period: 10
D/CALCFPS (  118): ignorethresh_us: 500000

thats the closest i could find. I believe you but dastin can confirm that while this is not the right fix as now pointed out, it does fix the live wallpaper issue. i still want to figure out the correct way to fix the bug

**Comment by Albinoman887** [comment]
so obviously this is NOT correct, note the 19xxxxxxx htz refresh rate, so how can i fix this live wallpaper issue. any other idea on what could be causing it

**Comment by Albinoman887** [comment]
@dastin1015 need your input

**Comment by arco** [comment]
The frame rate value is way off, that's for sure. This was with this revert
patch?
You might want to try a build using  fb.h from your kernel in the device
include overlay.

**Comment by dastin1015** [comment]
arco I believe I saw you were running a mr1 kernel for the msm7x30 architecture right? I believe part of the problem we are using a kernel for msm8660 with older drivers. Updating the kernel will more than likely help, but I don't have the necessary skills or know-how to do so.

**Comment by Albinoman887** [comment]
ok, just cuz i'm lazy, where is the fb.h is it just in the main include folder insde the kernel or like mach-msm

**Comment by Albinoman887** [comment]
mvn found it

**Comment by arco** [comment]
It's in the main include/linux folder.

**Comment by Albinoman887** [comment]
ya i got it, about to try about a build, takes a bit though. since i got your attention , not as big a priority but do you have any idea why we get video tearing with hd videos? it usually doesnt happen right away but after about 10mins it comes with a vengence. I have run a logcat and i always say pmem align failed at the begining of the video playing cant figure out what is causing it though

**Comment by Albinoman887** [comment]
using fb.h in the incudes for device tree i get 0 Htz :(

I/gralloc (  118): using (fd=21)
I/gralloc (  118): id           = msmfb40_90201
I/gralloc (  118): xres         = 540 px
I/gralloc (  118): yres         = 960 px
I/gralloc (  118): xres_virtual = 544 px
I/gralloc (  118): yres_virtual = 2880 px
I/gralloc (  118): bpp          = 32
I/gralloc (  118): r            =  0:8
I/gralloc (  118): g            =  8:8
I/gralloc (  118): b            = 16:8
I/gralloc (  118): width        = 53 mm (258.792450 dpi)
I/gralloc (  118): height       = 95 mm (256.673676 dpi)
I/gralloc (  118): refresh rate = 0.00 Hz
D/CALCFPS (  118): DEBUG_CALC_FPS: 0
D/CALCFPS (  118): period: 10
D/CALCFPS (  118): ignorethresh_us: 500000
D/CALCFPS (  118): DEBUG_CALC_FPS: 0
D/CALCFPS (  118): period: 10
D/CALCFPS (  118): ignorethresh_us: 500000

**Comment by arco** [comment]
If I apply this revert, I also get the 1986356224.00 Hz fps thing. If I still have this revert applied, and copies fb.h from my kernel to the include overlay for my device, then it reports the correct fps. So either way, reverting this or not, all is good on my side. No issues with live wallpapers either.

I was looking at your kernel, and there's a few patches I'm not so sure about whether is needed or not, as they might be the cause for your issues. I'm thinking about the following ones:

https://github.com/Team-Hydra/android_kernel_htc_msm7x30-3.0/commit/6437ed47f68e6cc8e3c153eb2817bf190db4a781
https://github.com/Team-Hydra/android_kernel_htc_msm7x30-3.0/commit/b0faec0fcb016e399076a4e59a65e64db9023f5c
https://github.com/Team-Hydra/android_kernel_htc_msm7x30-3.0/commit/c857db1482cddcd16734bee4cadf089b99d3c835

Maybe try reverting those.

About video tearing, I don't know. I used to have the pmem aligned error too, but I applied a patch from CAF which fixed that. Haven't seen the error since. The patch is already in display-legacy: https://github.com/arco/android_hardware_qcom_display-legacy/commit/0a8e1baaa3f4fa044ff4f8c409585ec69896985d

**Comment by Albinoman887** [comment]
just to be clear. i'm talking pyramid right now. so my kernel is actually android_kernel_htc_pyramid

**Comment by Albinoman887** [comment]
wheres the best place to look for caf patches. did you just pull it from cyanogens display-caf repo

**Comment by arco** [comment]
Ah right, then just disregard that. :)
I compared that fb.h with mine, and they are both the same.

**Comment by arco** [comment]
display-legacy is an exact copy of display from CM-10, with changes to
compile cleanly in CM-10.1 and with some additional patches. For patches I
use CAF's display repo.

https://www.codeaurora.org/gitweb/quic/la/?p=platform/hardware/qcom/display.git;a=summary

For this legacy branch, their jb_rel branch is most appropriate.

**Comment by Albinoman887** [comment]
lame. tried with fb.h again. still just get 0 htz. must be because we are
on different devices

**Comment by Albinoman887** [comment]
also my logcat is full of these warnings

W/SurfaceFlinger(  118): HWC_FRAMEBUFFER_TARGET found in hwc list (index=0)
W/SurfaceFlinger(  118): HWC_FRAMEBUFFER_TARGET found in hwc list (index=1)
W/SurfaceFlinger(  118): HWC_FRAMEBUFFER_TARGET found in hwc list (index=2)
W/SurfaceFlinger(  118): HWC_FRAMEBUFFER_TARGET found in hwc list (index=0)
W/SurfaceFlinger(  118): HWC_FRAMEBUFFER_TARGET found in hwc list (index=1)
W/SurfaceFlinger(  118): HWC_FRAMEBUFFER_TARGET found in hwc list (index=2)

**Comment by Albinoman887** [comment]
sorry to keep bugging you. but do you have the issue where the OSD of mx
video player or other players for that matter dissapear unless you disable
hw overlays in dev options? before we switched to your repo this wasn't the
case. any idea what commit might be causing it? as there isnt MUCH
difference between your repo and our old one i'm a little confused why this
is happening

**Comment by arco** [comment]
Nope, no problems with overlays here. I would suggest trying to revert one patch at a time, and see if there's any difference. Or look into the video drivers in your kernel.

**Comment by Albinoman887** [comment]
Yeah I just tried reverting all the overlay and hwc patches but still the
same, I'm going to revert back to just where you set it up for legacy and
slowly cherry pick in new changes I'm just kind of flying blind though on
what to try first etc

**Comment by Albinoman887** [comment]
so reverting these 4 commits fixed the overlay issue. now to narrow down
which one, here are the ones i reverted in no particular order

 "hwcomposer : Synchronize EventThread, and hwcVsyncThread"

 "hwcomposer: Mark Video layer to GPU if any other layer is marked with GPU"

"libcopybit: draw full layer if dirty region list is long"

"hwcomposer: fixes for hwc c2d composition"

"liboverlay: Use camera heap for targets without mm heap."

( i guess there were 5, some obviously had nothing to do with it like the
syncronize eventthread one but yeah.. those are the ones. now to narrow
down and figure out why. oh and i still have the log spam about HWC in
framebuffer target or whatever its saying

**Pull request closed without merging**
