### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by alviteri**
the address are incorrect 

Conflict here 

Libtilerenderer/Android.mk
-        frameworks/base/include/utils \
-        frameworks/native/include/utils \

and here
-        frameworks/base/opengl/include/GLES2
-        frameworks/native/opengl/include/GLES2

### CODE REVIEW

**Comment by arco** [comment]
The tilerenderer is actually obsolete in JB, and are not being compiled. So this won't make any difference.

**Comment by alviteri** [comment]
So USE_OPENGL_RENDERER isn't needed ?

**Comment by arco** [comment]
It is still needed, because it's used elsewhere.

**Comment by alviteri** [comment]
ok thanks arco

**Pull request closed without merging**
